export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';

export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';
export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';

export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';
export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';
export const SUCCESS_SIGN_OUT = 'SUCCESS_SIGN_OUT';
export const ERROR_SIGN_OUT = 'ERROR_SIGN_OUT';

export const REQUEST_FETCH_BOOKS = 'REQUEST_FETCH_BOOKS';
export const SUCCESS_FETCH_BOOKS = 'SUCCESS_FETCH_BOOKS';
export const ERROR_FETCH_BOOKS = 'ERROR_FETCH_BOOKS';

export const REQUEST_FETCH_BOOK = 'REQUEST_FETCH_BOOK';
export const SUCCESS_FETCH_BOOK = 'SUCCESS_FETCH_BOOK';
export const ERROR_FETCH_BOOK = 'ERROR_FETCH_BOOK';

export const CLEAR_BOOKS = 'CLEAR_BOOKS_STATE';
export const CLEAR_CURRENT_BOOK = 'CLEAR_CURRENT_BOOK';

export const REQUEST_EDIT_BOOK = 'REQUEST_EDIT_BOOK';
export const SUCCESS_EDIT_BOOK = 'SUCCESS_EDIT_BOOK';
export const ERROR_EDIT_BOOK = 'ERROR_EDIT_BOOK';

export const REQUEST_CREATE_BOOK = 'REQUEST_CREATE_BOOK';
export const SUCCESS_CREATE_BOOK = 'SUCCESS_CREATE_BOOK';
export const ERROR_CREATE_BOOK = 'ERROR_CREATE_BOOK';

export const REQUEST_DELETE_BOOK = 'REQUEST_DELETE_BOOK';
export const SUCCESS_DELETE_BOOK = 'SUCCESS_DELETE_BOOK';
export const ERROR_DELETE_BOOK = 'ERROR_DELETE_BOOK';


